TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += lvremote_num.proto
DATA += lvremote_string.proto

#=======================================
include $(TOP)/configure/RULES
