TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install template and protocol
DATA += lvremote_num.proto
DATA += lvremote_string.proto
DATA += lvremote_array.template
DATA += lvremote_binary.template
DATA += lvremote_double.template
DATA += lvremote_enum.template
DATA += lvremote_header.template
DATA += lvremote_string.template

#=======================================

# DB for testing
DB += lvremotetest.db

#=======================================
include $(TOP)/configure/RULES
